import { MarkdownPlugin } from '@platejs/markdown'
import remarkGfm from 'remark-gfm'
import remarkMath from 'remark-math'

// KaTeX's stylesheet, needed to render math at all (unstyled KaTeX output is
// a soup of unpositioned spans). This module is only ever reached via the
// lazy `markdown-editor-pane` chunk (see that file's `lazy()` call site in
// editor-pane.tsx) — never imported from the app entry — so this ships with
// that chunk, not the entry bundle. Do NOT hoist this import (or MathKit's)
// to anything imported eagerly; `bunx vite build` + a grep of the entry
// chunk for `platejs`/`katex` is the standing gate on that.
import 'katex/dist/katex.min.css'

// GFM-core node/mark kits generated by the shadcn registry (Task 1).
// `BasicNodesKit` already equals `[...BasicBlocksKit, ...BasicMarksKit]`, so
// it alone covers headings/paragraphs and marks (bold/italic/etc) — do not
// also import BasicMarksKit, that would double-register the mark plugins.
// `ListKit` already composes `IndentKit` as a dependency (task-list indent).
import { BasicNodesKit } from '@/components/editor/plugins/basic-nodes-kit'
import { BlockMenuKit } from '@/components/editor/plugins/block-menu-kit'
import { BlockPlaceholderKit } from '@/components/editor/plugins/block-placeholder-kit'
import { CalloutKit } from '@/components/editor/plugins/callout-kit'
import { CodeBlockKit } from '@/components/editor/plugins/code-block-kit'
import { FloatingToolbarKit } from '@/components/editor/plugins/floating-toolbar-kit'
import { LinkKit } from '@/components/editor/plugins/link-kit'
import { ListKit } from '@/components/editor/plugins/list-kit'
import { MathKit } from '@/components/editor/plugins/math-kit'
import { SlashKit } from '@/components/editor/plugins/slash-kit'
import { TableKit } from '@/components/editor/plugins/table-kit'
import { HtmlKit } from './html-node'
import { calloutMarkdownRules } from './markdown-callout-rules'
import { htmlMarkdownRules } from './markdown-html-rules'
import { MarkdownImageKit } from './markdown-image-node'
import { underlineMarkdownRules } from './markdown-underline-rules'

/** GFM-core plugin set shared by the live editor and the round-trip tests, so
 *  both exercise identical serialization. Extended plugins (mermaid,
 *  footnotes) are added in later slices.
 *
 *  The Notion-style block affordances (Task 13) — drag handle, `/` menu,
 *  block context menu, selection toolbar, empty-line hint — are pure
 *  UI/interaction plugins layered on top: none of them touch how a node
 *  round-trips to markdown, so they're safe to sit alongside the round-trip
 *  test's own plugin list unchanged. */
export const markdownPlugins = [
  ...BasicNodesKit,
  ...ListKit,
  ...TableKit,
  ...CodeBlockKit,
  ...LinkKit,
  ...MathKit,
  ...CalloutKit,
  ...HtmlKit,
  ...MarkdownImageKit,
  ...SlashKit,
  ...BlockMenuKit,
  ...FloatingToolbarKit,
  ...BlockPlaceholderKit,
  MarkdownPlugin.configure({
    options: {
      remarkPlugins: [remarkGfm, remarkMath],
      // @platejs/markdown defaults to `_` for emphasis, and remark-stringify
      // defaults to `*` for bullets. Both are valid CommonMark; pin them to
      // the conventional `*italic*` / `- item` style so a file the user
      // typed comes back byte-for-byte instead of being re-punctuated.
      remarkStringifyOptions: { emphasis: '*', bullet: '-' },
      // Overrides ONLY `blockquote`/`callout` (GitHub alert syntax — see
      // markdown-callout-rules.ts), `html` (render + byte-exact preserve of
      // raw HTML blocks — see markdown-html-rules.ts), and `underline`'s
      // `serialize` (the library's own default throws — see
      // markdown-underline-rules.ts). Plate merges `rules` per-key over its
      // own defaults, so no other node type is affected.
      rules: { ...calloutMarkdownRules, ...htmlMarkdownRules, ...underlineMarkdownRules },
    },
  }),
]
