// @generated by native/tools/protogen — DO NOT EDIT

/**
 * Envelope is the uniform response body returned by every v0 handler:
 * success is true for query and mutation responses and false for errors,
 * error carries the message on failure, and data carries the payload.
 */
export interface Envelope<T> {
  success: boolean;
  error?: string;
  data?: T;
}

/**
 * MutationID is the fixed data shape of a mutation response:
 * the id of the affected entity.
 */
export interface MutationID {
  id: string;
}
