// @generated by native/tools/protogen — DO NOT EDIT

/**
 * CreateItemBody is a named request body.
 */
export interface CreateItemBody {
  /**
   * Name is required.
   */
  name: string;
  /**
   * Status is optional.
   */
  status?: Status;
}

/**
 * Item exercises every field shape the generator has to lower.
 */
export interface Item {
  /**
   * ID is the entity id.
   */
  id: string;
  /**
   * CreatedAt is when it was created.
   */
  createdAt: string;
  meta: Meta;
  /**
   * Name is a plain required string.
   */
  name: string;
  /**
   * Description is omitted when empty.
   */
  description?: string;
  /**
   * Parent is a pointer, so it can be null or absent.
   */
  parent?: string | null;
  /**
   * Child is a pointer to a struct with no omitempty: null, never absent.
   */
  child?: Nested | null;
  /**
   * Tags is a slice; a nil slice marshals as null.
   */
  tags: string[] | null;
  /**
   * Items is a slice of structs, omitted when empty.
   */
  items?: Nested[];
  /**
   * Counts is a map of ints.
   */
  counts: Record<string, number> | null;
  /**
   * Extra is an untyped map: arbitrary JSON.
   */
  extra?: Record<string, unknown>;
  /**
   * Raw is a raw JSON message.
   */
  raw?: unknown;
  /**
   * Blob is a byte slice, which encoding/json base64-encodes to a string.
   */
  blob?: string;
  /**
   * Status is the enum.
   */
  status?: Status;
  /**
   * Kind is a named string with no constants.
   */
  kind: Untagged;
  /**
   * Type collides with a Rust keyword and forces an explicit rename.
   */
  type: string;
  /**
   * Size is an int64: a JSON number, not a string.
   */
  size: number;
  /**
   * Ratio is a float.
   */
  ratio: number;
  /**
   * Done is a bool omitted when false.
   */
  done?: boolean;
}

/**
 * Lossy carries a field the generator cannot lower: an anonymous struct nested
 * inside a slice has no name to emit, so the field is dropped and the type is
 * reported INCOMPLETE rather than quietly shipped a field short.
 */
/**
 * INCOMPLETE: protogen could not lower every field of this type.
 * - example.com/fixture/types.Lossy.Rows: field type []struct{Value string "json:\"value\""} did not resolve, so the field is missing from the generated struct
 */
export interface Lossy {
  /**
   * Name is fine.
   */
  name: string;
}

/**
 * Meta is embedded into Item WITH a json tag, so it stays a nested object.
 */
export interface Meta {
  /**
   * Author is who made the change.
   */
  author: string;
}

/**
 * Nested is a plain struct used as a field type.
 */
export interface Nested {
  /**
   * Label is the display label.
   */
  label: string;
  /**
   * Count is a counter.
   */
  count: number;
}

/**
 * Status is a named string type with a package-level constant set, which is
 * what makes it an enum rather than a bare string alias.
 */
export type Status =
  | "locked"
  | "new"
  | "pr-conflicts"
  | (string & {});

/**
 * TreeNode is self-referential, which the transitive closure must not recurse
 * into forever.
 */
export interface TreeNode {
  /**
   * Name is the node name.
   */
  name: string;
  /**
   * Children are the child nodes.
   */
  children: TreeNode[] | null;
}

/**
 * Untagged is a named string type with no constants: an alias, not an enum.
 */
export type Untagged = string;
