// @generated by native/tools/protogen — DO NOT EDIT

import type * as fixture_types from "./fixture_types";

/**
 * outlineResponse is the payload of GET /outline. It is written by hand rather
 * than through libs.WriteQueryOK, which is the whole point of it: a handler
 * that streams its envelope straight into the response writer never touches
 * gin's JSON render, and protogen used to classify exactly that as a body-less
 * success and drop the payload's types on the floor.
 */
export interface OutlineResponse {
  /**
   * Files is the outline of every changed file.
   */
  files: fixture_types.Nested[] | null;
}

/**
 * RenameItemRequest is the anonymous request body RenameItem binds for PATCH /v0/projects/:projectId/items/:id.
 */
export interface RenameItemRequest {
  name: string;
  force?: boolean;
}

/**
 * StageRequest is the anonymous request body Stage binds for POST /v0/projects/:projectId/stage.
 */
export interface StageRequest {
  paths: string[] | null;
}
