// @generated by native/tools/protogen — DO NOT EDIT

/**
 * RenameItemRequest is the anonymous request body RenameItem binds for PATCH /v0/projects/:projectId/items/:id.
 */
export interface RenameItemRequest {
  name: string;
  force?: boolean;
}

/**
 * StageRequest is the anonymous request body Stage binds for POST /v0/projects/:projectId/stage.
 */
export interface StageRequest {
  paths: string[] | null;
}
