// @generated by native/tools/protogen — DO NOT EDIT
//
// Wire DTOs for the Crowbar daemon's v0 HTTP surface, generated from the Go
// handlers. One namespace per Go package, so type names from different
// packages can never collide.
//
// Encoding notes, all of which mirror what encoding/json actually does:
//   * time.Time is a string (RFC 3339, as time.Time's MarshalJSON writes it).
//   * int64/uint64 are numbers, NOT strings: the daemon uses no `,string`
//     tags, so encoding/json emits them as JSON numbers. Values beyond
//     2^53 lose precision in JavaScript; none of the daemon's int64 fields
//     carry such values today.
//   * []byte is a string (encoding/json base64-encodes it).
//   * A nil Go slice or map marshals as null, so non-optional container
//     fields are typed `T[] | null`.

export * as fixture_handlers from "./fixture_handlers";
export * as fixture_libs from "./fixture_libs";
export * as fixture_types from "./fixture_types";
export * as gin_gonic_gin from "./gin_gonic_gin";
