import type { SettingSearchRecord } from '../types/search'

export const settingsSearchIndex: SettingSearchRecord[] = [
  // Editor Settings
  {
    id: 'editor-auto-save',
    tab: 'editor',
    section: 'Saving',
    label: 'Auto Save',
    description: 'Automatically save files when editing',
    keywords: ['save', 'automatic', 'files'],
  },
  {
    id: 'editor-font-family',
    tab: 'editor',
    section: 'Typography',
    label: 'Editor Font Family',
    description: 'Font family for code editor',
    keywords: ['font', 'editor', 'code', 'typography', 'family', 'monospace'],
  },
  {
    id: 'editor-font-size',
    tab: 'editor',
    section: 'Typography',
    label: 'Font Size',
    description: 'Editor font size in pixels',
    keywords: ['font', 'size', 'editor', 'typography'],
  },
  {
    id: 'editor-markdown-font-size',
    tab: 'editor',
    section: 'Markdown',
    label: 'Markdown Font Size',
    description: 'Base text size for the rich markdown editor, in pixels',
    keywords: ['markdown', 'md', 'font', 'size', 'text', 'typography', 'plate', 'document'],
  },
  {
    id: 'editor-line-height',
    tab: 'editor',
    section: 'Typography',
    label: 'Line Height',
    description: 'Editor line height multiplier',
    keywords: ['line', 'height', 'spacing', 'editor', 'typography'],
  },
  {
    id: 'editor-tab-size',
    tab: 'editor',
    section: 'Typography',
    label: 'Tab Size',
    description: 'Number of spaces per tab',
    keywords: ['tab', 'size', 'indentation', 'spaces'],
  },
  {
    id: 'editor-word-wrap',
    tab: 'editor',
    section: 'Display',
    label: 'Word Wrap',
    description: 'Wrap lines that exceed viewport width',
    keywords: ['word', 'wrap', 'lines', 'display'],
  },
  {
    id: 'editor-line-numbers',
    tab: 'editor',
    section: 'Display',
    label: 'Line Numbers',
    description: 'Show line numbers in the editor',
    keywords: ['line', 'numbers', 'gutter', 'display'],
  },
  {
    id: 'editor-render-whitespace',
    tab: 'editor',
    section: 'Display',
    label: 'Render Whitespace',
    description: 'Show visible markers for spaces and tabs',
    keywords: ['whitespace', 'spaces', 'tabs', 'invisible', 'render', 'display'],
  },
  {
    id: 'editor-render-indent-guides',
    tab: 'editor',
    section: 'Display',
    label: 'Indent Guides',
    description: 'Show vertical guides for indentation levels',
    keywords: ['indent', 'guides', 'indentation', 'tabs', 'spaces', 'display'],
  },
  {
    id: 'editor-semantic-highlighting',
    tab: 'editor',
    section: 'Display',
    label: 'Semantic Highlighting',
    description: 'Color functions, types, and properties using the Tree-sitter tokenizer',
    keywords: ['semantic', 'highlighting', 'syntax', 'tree-sitter', 'colors', 'tokens', 'display'],
  },
  {
    id: 'editor-highlight-occurrences',
    tab: 'editor',
    section: 'Display',
    label: 'Highlight Occurrences',
    description: 'Highlight visible matches for the word under the cursor',
    keywords: ['highlight', 'occurrences', 'matches', 'word', 'symbol', 'cursor'],
  },
  {
    id: 'editor-show-minimap',
    tab: 'editor',
    section: 'Display',
    label: 'Show Minimap',
    description: 'Show a minimap overview of the code on the right side of the editor',
    keywords: ['minimap', 'overview', 'code', 'preview', 'display'],
  },
  {
    id: 'editor-max-open-tabs',
    tab: 'editor',
    section: 'Tabs',
    label: 'Max Open Tabs',
    description: 'Maximum number of tabs before oldest closes',
    keywords: ['tabs', 'limit', 'maximum', 'open'],
  },

  // File Tree Settings
  {
    id: 'file-tree-indent-size',
    tab: 'file-explorer',
    section: 'Display',
    label: 'Indent Size',
    description: 'Pixels per nesting level in the file tree',
    keywords: ['indent', 'indentation', 'nesting', 'depth', 'tree', 'file explorer', 'spacing'],
  },
  {
    id: 'file-tree-show-hidden-files',
    tab: 'file-explorer',
    section: 'Display',
    label: 'Show Hidden Files',
    description: 'Show dotfiles and hidden directories in the file tree',
    keywords: ['hidden', 'dotfiles', 'dotfile', 'files', 'folders', 'directories', 'visibility'],
  },
  {
    id: 'file-tree-compact-folders',
    tab: 'file-explorer',
    section: 'Display',
    label: 'Compact Folders',
    description: 'Collapse single-child folder chains in the file tree',
    keywords: ['compact', 'folders', 'directories', 'single child', 'collapse', 'nested'],
  },
  {
    id: 'file-tree-density',
    tab: 'file-explorer',
    section: 'Display',
    label: 'Density',
    description: 'Choose file tree row spacing',
    keywords: ['density', 'spacing', 'compact', 'comfortable', 'rows', 'height'],
  },
  {
    id: 'file-tree-respect-gitignore',
    tab: 'file-explorer',
    section: 'Display',
    label: 'Respect .gitignore',
    description: 'Hide files matched by root and nested .gitignore files',
    keywords: ['gitignore', '.gitignore', 'ignored', 'git', 'files', 'visibility', 'exclude'],
  },
  {
    id: 'file-tree-hidden-file-patterns',
    tab: 'file-explorer',
    section: 'Filters',
    label: 'Hidden File Patterns',
    description: 'Files matching these glob patterns will be hidden from the file tree',
    keywords: ['hidden', 'files', 'patterns', 'glob', 'filter', 'exclude'],
  },
  {
    id: 'file-tree-hidden-directory-patterns',
    tab: 'file-explorer',
    section: 'Filters',
    label: 'Hidden Directory Patterns',
    description: 'Directories matching these glob patterns will be hidden from the file tree',
    keywords: ['hidden', 'directories', 'folders', 'patterns', 'glob', 'filter', 'exclude'],
  },
  {
    id: 'git-show-status-in-file-tree',
    tab: 'git',
    section: 'File Tree',
    label: 'Show Git Status In File Tree',
    description: 'Display Git decorations in Files',
    keywords: ['git', 'file tree', 'files', 'file explorer', 'decorations', 'status'],
  },
  {
    id: 'git-compact-status-badges',
    tab: 'git',
    section: 'Git View',
    label: 'Compact Git Status Badges',
    description: 'Use denser diff stats and staged indicators in the Git panel',
    keywords: ['git', 'compact', 'badges', 'status', 'dense'],
  },

  // Appearance Settings
  {
    id: 'appearance-theme',
    tab: 'appearance',
    section: 'Theme',
    label: 'Color Theme',
    description: 'Choose your preferred color theme',
    keywords: ['theme', 'color', 'appearance', 'dark', 'light'],
  },
  {
    id: 'appearance-icon-theme',
    tab: 'appearance',
    section: 'Theme',
    label: 'Icon Theme',
    description: 'Icons displayed in the file tree and tabs',
    keywords: ['icon', 'theme', 'file', 'tree', 'tabs'],
  },
  {
    id: 'appearance-ui-font',
    tab: 'appearance',
    section: 'Typography',
    label: 'UI Font Family',
    description: 'Font family for UI elements (file tree, markdown, etc.)',
    keywords: ['font', 'ui', 'typography', 'family'],
  },
  {
    id: 'appearance-ui-font-size',
    tab: 'appearance',
    section: 'Typography',
    label: 'UI Font Size',
    description: 'Adjust UI text and icon scale in 0.5px steps',
    keywords: ['font', 'size', 'ui', 'icon', 'scale', 'typography'],
  },
  {
    id: 'appearance-sidebar-position',
    tab: 'appearance',
    section: 'Layout',
    label: 'Sidebar Position',
    description: 'Choose where to position the sidebar',
    keywords: ['sidebar', 'position', 'left', 'right', 'layout'],
  },
  {
    id: 'appearance-workspace-keep-alive',
    tab: 'appearance',
    section: 'Performance',
    label: 'Keep Workspaces in Memory',
    description:
      'Keep recently visited workspaces mounted so switching back is instant; 0 disables it',
    keywords: [
      'workspace',
      'workspaces',
      'keep',
      'memory',
      'switch',
      'switching',
      'performance',
      'cache',
      'ttl',
      'keep-alive',
    ],
  },

  // Language Settings
  {
    id: 'language-format-on-save',
    tab: 'editor',
    section: 'Code Formatting',
    label: 'Format on Save',
    description: 'Automatically format code when saving',
    keywords: ['format', 'save', 'automatic', 'formatting', 'prettier'],
  },
  {
    id: 'language-lint-on-save',
    tab: 'editor',
    section: 'Code Formatting',
    label: 'Lint on Save',
    description: 'Run linter when saving files',
    keywords: ['lint', 'linter', 'save', 'eslint', 'check'],
  },
  {
    id: 'language-auto-completion',
    tab: 'editor',
    section: 'IntelliSense',
    label: 'Auto Completion',
    description: 'Show completion suggestions while typing',
    keywords: ['autocomplete', 'completion', 'intellisense', 'suggestions'],
  },
  {
    id: 'language-parameter-hints',
    tab: 'editor',
    section: 'IntelliSense',
    label: 'Parameter Hints',
    description: 'Show function parameter hints',
    keywords: ['parameter', 'hints', 'intellisense', 'function'],
  },

  // Provider Settings
  //
  // Both controls the Providers tab exposes. Without them the tab was invisible
  // to this search: typing "provider" scored nothing, the rail filtered down to
  // "No matching settings", and the search HID the one tab that matched. The two
  // records share a keyword set because a user hunting for either says the same
  // words — the CLI's name as often as the concept's.
  {
    id: 'providers-priority-order',
    tab: 'providers',
    section: 'Providers',
    label: 'Provider Priority',
    description: 'Drag to set which provider a new chat opens first',
    keywords: [
      'provider',
      'agent',
      'cli',
      'claude',
      'codex',
      'priority',
      'order',
      'reorder',
      'default',
    ],
  },
  {
    id: 'providers-enabled',
    tab: 'providers',
    section: 'Providers',
    label: 'Enable Provider',
    description: 'Turn a provider off to hide it from every New chat surface',
    keywords: ['provider', 'agent', 'cli', 'claude', 'codex', 'enable', 'disable', 'off', 'hide'],
  },

  // Terminal Settings
  {
    id: 'terminal-font-family',
    tab: 'terminal',
    section: 'Typography',
    label: 'Terminal Font Family',
    description: 'Font family for the integrated terminal',
    keywords: ['terminal', 'font', 'family', 'monospace', 'nerd font'],
  },
  {
    id: 'terminal-font-size',
    tab: 'terminal',
    section: 'Typography',
    label: 'Terminal Font Size',
    description: 'Terminal font size in pixels',
    keywords: ['terminal', 'font', 'size'],
  },
  {
    id: 'terminal-line-height',
    tab: 'terminal',
    section: 'Typography',
    label: 'Terminal Line Height',
    description: 'Line height multiplier for terminal',
    keywords: ['terminal', 'line', 'height', 'spacing'],
  },
  {
    id: 'terminal-letter-spacing',
    tab: 'terminal',
    section: 'Typography',
    label: 'Terminal Letter Spacing',
    description: 'Additional spacing between characters in terminal',
    keywords: ['terminal', 'letter', 'spacing', 'characters'],
  },
  {
    id: 'terminal-scrollback',
    tab: 'terminal',
    section: 'Typography',
    label: 'Terminal Scrollback',
    description: 'How many terminal history lines to retain',
    keywords: ['terminal', 'scrollback', 'history', 'buffer', 'lines'],
  },
  {
    id: 'terminal-cursor-style',
    tab: 'terminal',
    section: 'Cursor',
    label: 'Terminal Cursor Style',
    description: 'Shape of the terminal cursor',
    keywords: ['terminal', 'cursor', 'style', 'block', 'underline', 'bar'],
  },
  {
    id: 'terminal-cursor-blink',
    tab: 'terminal',
    section: 'Cursor',
    label: 'Terminal Cursor Blink',
    description: 'Whether the terminal cursor should blink',
    keywords: ['terminal', 'cursor', 'blink', 'blinking'],
  },
  {
    id: 'terminal-cursor-width',
    tab: 'terminal',
    section: 'Cursor',
    label: 'Terminal Cursor Width',
    description: 'Thickness of the terminal cursor',
    keywords: ['terminal', 'cursor', 'width', 'thickness', 'bar'],
  },
]
