export const DEFAULT_UI_FONT_FAMILY = "IBM Plex Sans Variable";
export const DEFAULT_MONO_FONT_FAMILY = "JetBrains Mono Variable";

export const DEFAULT_CODE_FONT_SIZE = 14;
export const DEFAULT_UI_FONT_SIZE_OFFSET = 1;
export const DEFAULT_UI_FONT_SIZE = DEFAULT_CODE_FONT_SIZE + DEFAULT_UI_FONT_SIZE_OFFSET;
export const DEFAULT_TERMINAL_FONT_SIZE = DEFAULT_CODE_FONT_SIZE;
