// Package ledger implements the per-chat, append-only, provider-tagged store of
// conversation turns Crowbar derives from vendor-CLI hooks (agentic-engine
// descriptor-v2 §7). Crowbar builds this record itself; it never reads a file
// the vendor CLI wrote.
package ledger

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"
)

// Turn is one conversation turn recorded from a hook.
type Turn struct {
	Role     string `json:"role"` // "user" | "assistant"
	Provider string `json:"provider"`
	// RunnerID is internal correlation metadata for durable prompt delivery.
	// It is not part of the React message DTO and older ledger rows decode with
	// it empty. Provider payloads never choose it; Crowbar supplies the runner
	// that delivered the hook.
	RunnerID string `json:"runner_id,omitempty"`
	// SessionID attributes turn existence to the provider-native conversation
	// current on that runner. It stays internal to Crowbar's resume decisions and
	// is intentionally absent from the React DTO.
	SessionID string `json:"session_id,omitempty"`
	// DeliveryID is the Crowbar hook relay's durable idempotency key. It is
	// generated by Crowbar before POST, never by a provider, and omitted from the
	// React DTO. Retries reuse it so a response loss cannot duplicate a turn.
	DeliveryID string    `json:"delivery_id,omitempty"`
	Text       string    `json:"text"`
	At         time.Time `json:"at"`
}

// Message is one ledger turn together with its chat-local append sequence.
// Sequence comes from the ledger entry name Crowbar owns; provider payloads do
// not get to choose it.
type Message struct {
	Sequence int
	Turn
}

// Page is a bounded chronological window of messages. Cursor is the greatest
// sequence in Items and OldestCursor is the least. HasMore means there are more
// messages in the direction of the request: newer for an after page and older
// for a before/initial page.
type Page struct {
	Cursor       int
	OldestCursor int
	HasMore      bool
	Items        []Message
}

// Speaker is the attribution this turn is rendered under: the bare role, or
// "assistant (<provider>)" when a vendor CLI produced it and named itself.
//
// It is a method rather than a fmt call at each render site because a ledger has
// more than one consumer now — RenderConversation, and the agent tool surface's
// get_chat_log, which reads Turns directly so it can COUNT turns before
// rendering them. Both must attribute a speaker identically, or the same
// conversation reads as two different ones depending on who asked.
func (t Turn) Speaker() string {
	if t.Role == "assistant" && t.Provider != "" {
		return fmt.Sprintf("assistant (%s)", t.Provider)
	}
	return t.Role
}

// Ledger is a per-chat, append-only store of conversation turns.
type Ledger struct {
	dir      string
	appendMu *sync.Mutex
}

// Every Open of one chat ledger shares its append lock. Hooks and reads create
// short-lived Ledger handles, so a mutex stored only on the handle would not
// serialize concurrent runners choosing the next sequence.
var ledgerAppendLocks sync.Map // cleaned naturally at daemon restart; chat ids are never reused

// Open ensures the ledger directory exists and returns a handle to it.
func Open(dir string) (*Ledger, error) {
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return nil, fmt.Errorf("ledger: mkdir: %w", err)
	}
	lock, _ := ledgerAppendLocks.LoadOrStore(filepath.Clean(dir), &sync.Mutex{})
	return &Ledger{dir: dir, appendMu: lock.(*sync.Mutex)}, nil
}

// AppendTurn records one conversation turn. Empty text is a no-op (returns
// ("", nil)) so a provider that fires turn_stop with no final message never
// writes a blank entry. The %08d prefix keeps lexical == chronological order.
func (l *Ledger) AppendTurn(role, provider string, at time.Time, text string) (string, error) {
	return l.AppendRunnerTurn(role, provider, "", at, text)
}

// AppendRunnerTurn records a hook turn attributed to the Crowbar runner that
// delivered it. The public message read model intentionally omits RunnerID.
func (l *Ledger) AppendRunnerTurn(role, provider, runnerID string, at time.Time, text string) (string, error) {
	return l.AppendSessionTurn(role, provider, runnerID, "", at, text)
}

// AppendSessionTurn records both process and native-conversation attribution.
func (l *Ledger) AppendSessionTurn(
	role, provider, runnerID, sessionID string,
	at time.Time,
	text string,
) (string, error) {
	name, _, err := l.AppendDeliveredSessionTurn(
		role, provider, runnerID, sessionID, "", at, text,
	)
	return name, err
}

// AppendDeliveredSessionTurn atomically deduplicates one Crowbar hook delivery.
// appended=false means the same delivery already committed and is a successful
// replay. The delivery id is also embedded in the entry filename, making the
// durable check an O(number-of-entry-names) scan without unmarshalling history.
func (l *Ledger) AppendDeliveredSessionTurn(
	role, provider, runnerID, sessionID, deliveryID string,
	at time.Time,
	text string,
) (name string, appended bool, err error) {
	if text == "" {
		return "", false, nil
	}
	l.appendMu.Lock()
	defer l.appendMu.Unlock()
	names, err := l.entries()
	if err != nil {
		return "", false, err
	}
	if deliveryID != "" {
		suffix := "-" + deliveryID + ".turn"
		for _, existing := range names {
			if strings.HasSuffix(existing, suffix) {
				return existing, false, nil
			}
		}
	}
	seq := len(names) + 1
	rec, err := json.Marshal(Turn{
		Role: role, Provider: provider, RunnerID: runnerID, SessionID: sessionID,
		DeliveryID: deliveryID, Text: text, At: at.UTC(),
	})
	if err != nil {
		return "", false, fmt.Errorf("ledger: marshal turn: %w", err)
	}
	name = fmt.Sprintf("%08d-%s-%s-%s.turn", seq, at.UTC().Format("20060102T150405Z"), role, provider)
	if deliveryID != "" {
		name = strings.TrimSuffix(name, ".turn") + "-" + deliveryID + ".turn"
	}
	tmp, err := os.CreateTemp(l.dir, ".turn-*")
	if err != nil {
		return "", false, fmt.Errorf("ledger: write temp: %w", err)
	}
	tmpName := tmp.Name()
	defer func() { _ = os.Remove(tmpName) }()
	if err := tmp.Chmod(0o640); err != nil { //nolint:gosec // ledger entries are group-readable by design
		_ = tmp.Close()
		return "", false, fmt.Errorf("ledger: chmod temp: %w", err)
	}
	if _, err := tmp.Write(rec); err != nil {
		_ = tmp.Close()
		return "", false, fmt.Errorf("ledger: write: %w", err)
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return "", false, fmt.Errorf("ledger: sync: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return "", false, fmt.Errorf("ledger: close: %w", err)
	}
	if err := os.Rename(tmpName, filepath.Join(l.dir, name)); err != nil {
		return "", false, fmt.Errorf("ledger: commit: %w", err)
	}
	if err := syncDir(l.dir); err != nil {
		return "", false, err
	}
	return name, true, nil
}

// syncDir makes the atomic rename durable. Without the parent fsync a successful
// hook response can acknowledge a turn whose directory entry disappears after a
// power loss, leaving the native transcript and Crowbar's ledger inconsistent.
func syncDir(dir string) error {
	dh, err := os.Open(dir) //nolint:gosec // daemon-owned ledger directory
	if err != nil {
		return fmt.Errorf("ledger: open parent for sync: %w", err)
	}
	syncErr := dh.Sync()
	closeErr := dh.Close()
	if syncErr != nil || closeErr != nil {
		return fmt.Errorf("ledger: sync parent: %w", errors.Join(syncErr, closeErr))
	}
	return nil
}

func (l *Ledger) entries() ([]string, error) {
	des, err := os.ReadDir(l.dir)
	if err != nil {
		return nil, fmt.Errorf("ledger: readdir: %w", err)
	}
	var names []string
	for _, de := range des {
		if !de.IsDir() && filepath.Ext(de.Name()) == ".turn" {
			names = append(names, de.Name())
		}
	}
	sort.Strings(names)
	return names, nil
}

func (l *Ledger) nextSeq() (int, error) {
	names, err := l.entries()
	if err != nil {
		return 0, err
	}
	return len(names) + 1, nil
}

func (l *Ledger) readTurn(name string) (Turn, error) {
	data, err := os.ReadFile(filepath.Join(l.dir, name)) //nolint:gosec // name comes from entries() listing l.dir, not external input
	if err != nil {
		return Turn{}, fmt.Errorf("ledger: read %s: %w", name, err)
	}
	var tn Turn
	if err := json.Unmarshal(data, &tn); err != nil {
		return Turn{}, fmt.Errorf("ledger: unmarshal %s: %w", name, err)
	}
	return tn, nil
}

// Turns reads every recorded turn, oldest first.
//
// It exists for the agent tool surface's get_chat_log, which CAPS how much of a
// sibling chat it hands a model and therefore has to count turns before it
// renders any. Counting them back out of RenderConversation's text is not
// possible: turns are joined by a blank line and a turn's own body is free-form
// model prose containing blank lines routinely, so a reader splitting the
// rendering apart would report a turn count that is not true.
func (l *Ledger) Turns() ([]Turn, error) {
	names, err := l.entries()
	if err != nil {
		return nil, err
	}
	out := make([]Turn, 0, len(names))
	for _, n := range names {
		tn, err := l.readTurn(n)
		if err != nil {
			return nil, err
		}
		out = append(out, tn)
	}
	return out, nil
}

// Page reads a bounded message window in chronological order.
//
//   - after > 0 returns the first limit messages whose sequence is greater than
//     after (incremental refresh), and HasMore reports additional newer rows.
//   - before > 0 returns the newest limit messages whose sequence is less than
//     before (paging upward), and HasMore reports additional older rows.
//   - with neither cursor, it returns the newest limit messages and HasMore
//     reports whether older rows exist.
//
// after and before are mutually exclusive. The caller owns request validation;
// this method still rejects an ambiguous request so non-HTTP consumers cannot
// accidentally receive a misleading page.
func (l *Ledger) Page(after, before, limit int) (Page, error) {
	if after > 0 && before > 0 {
		return Page{}, fmt.Errorf("ledger: after and before are mutually exclusive")
	}
	if limit <= 0 {
		return Page{}, fmt.Errorf("ledger: limit must be positive")
	}

	names, err := l.entries()
	if err != nil {
		return Page{}, err
	}

	type namedMessage struct {
		name string
		seq  int
	}
	eligible := make([]namedMessage, 0, len(names))
	for _, name := range names {
		seq, err := sequenceFromName(name)
		if err != nil {
			return Page{}, err
		}
		if after > 0 && seq <= after {
			continue
		}
		if before > 0 && seq >= before {
			continue
		}
		eligible = append(eligible, namedMessage{name: name, seq: seq})
	}

	start, end := 0, len(eligible)
	hasMore := false
	if after > 0 {
		if end > limit {
			end = limit
			hasMore = true
		}
	} else if end > limit {
		start = end - limit
		hasMore = true
	}

	items := make([]Message, 0, end-start)
	for _, item := range eligible[start:end] {
		turn, err := l.readTurn(item.name)
		if err != nil {
			return Page{}, err
		}
		items = append(items, Message{Sequence: item.seq, Turn: turn})
	}

	page := Page{HasMore: hasMore, Items: items}
	if len(items) > 0 {
		page.OldestCursor = items[0].Sequence
		page.Cursor = items[len(items)-1].Sequence
	}
	return page, nil
}

// HasTurnAtOrAfter reports whether provider produced any real ledger turn in
// the currently bound native conversation. The current-conversation boundary
// is supplied by AgentRunner.CurrentSessionSince; this avoids treating an older
// conversation from the same provider as proof that a newly announced session
// is resumable.
func (l *Ledger) HasTurnAtOrAfter(provider string, since time.Time) (bool, error) {
	if provider == "" || since.IsZero() {
		return false, nil
	}
	names, err := l.entries()
	if err != nil {
		return false, err
	}
	for _, name := range names {
		turn, err := l.readTurn(name)
		if err != nil {
			return false, err
		}
		if turn.Provider == provider && !turn.At.Before(since) {
			return true, nil
		}
	}
	return false, nil
}

func sequenceFromName(name string) (int, error) {
	prefix, _, ok := strings.Cut(name, "-")
	if !ok || prefix == "" {
		return 0, fmt.Errorf("ledger: malformed entry name %q", name)
	}
	seq, err := strconv.Atoi(prefix)
	if err != nil || seq <= 0 {
		return 0, fmt.Errorf("ledger: malformed entry sequence %q", name)
	}
	return seq, nil
}

// RenderConversation reads every turn in order and renders a legible plain-text
// conversation for a receiving model.
func (l *Ledger) RenderConversation() ([]byte, error) {
	return l.render(time.Time{})
}

// RenderConversationAfter renders only the turns recorded strictly after cut —
// the "while you were away" gap handed to a provider being resumed into its OWN
// native session. That session already holds everything up to the moment it was
// switched out, so replaying the whole ledger to it would duplicate its history;
// only what happened under OTHER providers since then is new information. A zero
// cut renders everything (RenderConversation). Returns empty (not an error) when
// nothing happened in the gap — the caller then injects nothing at all.
func (l *Ledger) RenderConversationAfter(cut time.Time) ([]byte, error) {
	return l.render(cut)
}

// LastEntryAt returns the FILE NAME of the last turn recorded at or before cut —
// the last turn a provider being resumed has already seen, and therefore the point
// it should start reading from. Empty when the ledger has nothing that old (the
// provider has seen nothing; it starts at the beginning).
//
// A name, not a body: a resumed provider is POINTED at the ledger rather than
// handed a copy of it, so all it needs is where to start.
func (l *Ledger) LastEntryAt(cut time.Time) (string, error) {
	names, err := l.entries()
	if err != nil {
		return "", err
	}
	last := ""
	for _, n := range names {
		tn, err := l.readTurn(n)
		if err != nil {
			return "", err
		}
		if cut.IsZero() || !tn.At.After(cut) {
			last = n
		}
	}
	return last, nil
}

// LastTurnAt returns when provider last spoke in this chat — the moment it left,
// and therefore the cut for the "while you were away" gap a resumed provider is
// handed. Zero when it never spoke.
//
// A zero return is also the answer to the OTHER question the resume path asks:
// "does this provider's conversation actually EXIST on disk?" A vendor CLI reports
// a session id the instant it starts, but only WRITES that conversation once there
// is at least one message — claude refuses `--resume <id>` for such a session with
// "No conversation found with session ID", which is exactly what killed a chat the
// user had never typed in. Crowbar records a turn from the very same hooks, so a
// provider with no turn here has nothing to resume and must be spawned fresh.
//
// It reads the ledger rather than runner history because the ledger is the record
// of what was actually SAID. Conversation history only knows when a conversation
// OPENED, and a provider that opens a conversation, says nothing, and is switched
// away from must not be resumed into it.
func (l *Ledger) LastTurnAt(provider string) (time.Time, error) {
	names, err := l.entries()
	if err != nil {
		return time.Time{}, err
	}
	var last time.Time
	for _, n := range names {
		tn, err := l.readTurn(n)
		if err != nil {
			return time.Time{}, err
		}
		if tn.Provider == provider && tn.At.After(last) {
			last = tn.At
		}
	}
	return last, nil
}

// LastTurnForSession proves that one specific native conversation has content.
// New ledgers carry session attribution. For an upgraded legacy ledger where a
// provider has no attributed turns at all, it falls back to provider-wide
// evidence so existing resumable chats do not lose continuity. Once any modern
// attributed turn exists for that provider, an empty newer session can no longer
// borrow proof from an older one.
func (l *Ledger) LastTurnForSession(provider, sessionID string) (time.Time, error) {
	names, err := l.entries()
	if err != nil {
		return time.Time{}, err
	}
	var matched, legacy time.Time
	hasAttributed := false
	for _, name := range names {
		turn, err := l.readTurn(name)
		if err != nil {
			return time.Time{}, err
		}
		if turn.Provider != provider {
			continue
		}
		if turn.SessionID != "" {
			hasAttributed = true
			if turn.SessionID == sessionID && turn.At.After(matched) {
				matched = turn.At
			}
		} else if turn.At.After(legacy) {
			legacy = turn.At
		}
	}
	if hasAttributed {
		return matched, nil
	}
	return legacy, nil
}

func (l *Ledger) render(cut time.Time) ([]byte, error) {
	turns, err := l.Turns()
	if err != nil {
		return nil, err
	}
	var out []byte
	for _, tn := range turns {
		if !cut.IsZero() && !tn.At.After(cut) {
			continue
		}
		out = append(out, []byte(tn.Speaker()+": "+tn.Text+"\n\n")...)
	}
	return out, nil
}
