/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as WorkspacesNewRouteImport } from './routes/workspaces/new'
import { Route as WorkspacesWsIdRouteImport } from './routes/workspaces/$wsId'
import { Route as ChatChatIdRouteImport } from './routes/chat/$chatId'
import { Route as WorkspacesWsIdIndexRouteImport } from './routes/workspaces/$wsId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesNewRoute = WorkspacesNewRouteImport.update({
  id: '/workspaces/new',
  path: '/workspaces/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWsIdRoute = WorkspacesWsIdRouteImport.update({
  id: '/workspaces/$wsId',
  path: '/workspaces/$wsId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWsIdIndexRoute = WorkspacesWsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspacesWsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/workspaces/$wsId': typeof WorkspacesWsIdRouteWithChildren
  '/workspaces/new': typeof WorkspacesNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/workspaces/$wsId/': typeof WorkspacesWsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/workspaces/new': typeof WorkspacesNewRoute
  '/projects': typeof ProjectsIndexRoute
  '/workspaces/$wsId': typeof WorkspacesWsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/workspaces/$wsId': typeof WorkspacesWsIdRouteWithChildren
  '/workspaces/new': typeof WorkspacesNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/workspaces/$wsId/': typeof WorkspacesWsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat/$chatId'
    | '/workspaces/$wsId'
    | '/workspaces/new'
    | '/projects/'
    | '/workspaces/$wsId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat/$chatId'
    | '/workspaces/new'
    | '/projects'
    | '/workspaces/$wsId'
  id:
    | '__root__'
    | '/'
    | '/chat/$chatId'
    | '/workspaces/$wsId'
    | '/workspaces/new'
    | '/projects/'
    | '/workspaces/$wsId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatChatIdRoute: typeof ChatChatIdRoute
  WorkspacesWsIdRoute: typeof WorkspacesWsIdRouteWithChildren
  WorkspacesNewRoute: typeof WorkspacesNewRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/new': {
      id: '/workspaces/new'
      path: '/workspaces/new'
      fullPath: '/workspaces/new'
      preLoaderRoute: typeof WorkspacesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$wsId': {
      id: '/workspaces/$wsId'
      path: '/workspaces/$wsId'
      fullPath: '/workspaces/$wsId'
      preLoaderRoute: typeof WorkspacesWsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$wsId/': {
      id: '/workspaces/$wsId/'
      path: '/'
      fullPath: '/workspaces/$wsId/'
      preLoaderRoute: typeof WorkspacesWsIdIndexRouteImport
      parentRoute: typeof WorkspacesWsIdRoute
    }
  }
}

interface WorkspacesWsIdRouteChildren {
  WorkspacesWsIdIndexRoute: typeof WorkspacesWsIdIndexRoute
}

const WorkspacesWsIdRouteChildren: WorkspacesWsIdRouteChildren = {
  WorkspacesWsIdIndexRoute: WorkspacesWsIdIndexRoute,
}

const WorkspacesWsIdRouteWithChildren = WorkspacesWsIdRoute._addFileChildren(
  WorkspacesWsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatChatIdRoute: ChatChatIdRoute,
  WorkspacesWsIdRoute: WorkspacesWsIdRouteWithChildren,
  WorkspacesNewRoute: WorkspacesNewRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
