/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellProjectsIndexRouteImport } from './routes/_shell/projects/index'
import { Route as ShellWorkspacesNewRouteImport } from './routes/_shell/workspaces/new'
import { Route as ShellWorkspacesWsIdRouteImport } from './routes/_shell/workspaces/$wsId'
import { Route as ShellChatChatIdRouteImport } from './routes/_shell/chat/$chatId'
import { Route as ShellWorkspacesWsIdIndexRouteImport } from './routes/_shell/workspaces/$wsId/index'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  path: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/_shell/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectsIndexRoute = ShellProjectsIndexRouteImport.update({
  id: '/_shell/projects/',
  path: '/projects/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellWorkspacesNewRoute = ShellWorkspacesNewRouteImport.update({
  id: '/_shell/workspaces/new',
  path: '/workspaces/new',
  getParentRoute: () => ShellRoute,
} as any)
const ShellWorkspacesWsIdRoute = ShellWorkspacesWsIdRouteImport.update({
  id: '/_shell/workspaces/$wsId',
  path: '/workspaces/$wsId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellChatChatIdRoute = ShellChatChatIdRouteImport.update({
  id: '/_shell/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellWorkspacesWsIdIndexRoute = ShellWorkspacesWsIdIndexRouteImport.update({
  id: '/_shell/workspaces/$wsId/',
  path: '/',
  getParentRoute: () => ShellWorkspacesWsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/': typeof ShellIndexRoute
  '/_shell/chat/$chatId': typeof ShellChatChatIdRoute
  '/_shell/workspaces/$wsId': typeof ShellWorkspacesWsIdRouteWithChildren
  '/_shell/workspaces/new': typeof ShellWorkspacesNewRoute
  '/_shell/projects/': typeof ShellProjectsIndexRoute
  '/_shell/workspaces/$wsId/': typeof ShellWorkspacesWsIdIndexRoute
}
export interface FileRoutesByTo {
  '/_shell': typeof ShellRouteWithChildren
  '/': typeof ShellIndexRoute
  '/_shell/chat/$chatId': typeof ShellChatChatIdRoute
  '/_shell/workspaces/new': typeof ShellWorkspacesNewRoute
  '/projects': typeof ShellProjectsIndexRoute
  '/workspaces/$wsId': typeof ShellWorkspacesWsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/': typeof ShellIndexRoute
  '/_shell/chat/$chatId': typeof ShellChatChatIdRoute
  '/_shell/workspaces/$wsId': typeof ShellWorkspacesWsIdRouteWithChildren
  '/_shell/workspaces/new': typeof ShellWorkspacesNewRoute
  '/_shell/projects/': typeof ShellProjectsIndexRoute
  '/_shell/workspaces/$wsId/': typeof ShellWorkspacesWsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/_shell'
    | '/_shell/'
    | '/_shell/chat/$chatId'
    | '/_shell/workspaces/$wsId'
    | '/_shell/workspaces/new'
    | '/_shell/projects/'
    | '/_shell/workspaces/$wsId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/_shell'
    | '/'
    | '/_shell/chat/$chatId'
    | '/_shell/workspaces/new'
    | '/projects'
    | '/workspaces/$wsId'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/'
    | '/_shell/chat/$chatId'
    | '/_shell/workspaces/$wsId'
    | '/_shell/workspaces/new'
    | '/_shell/projects/'
    | '/_shell/workspaces/$wsId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: '/_shell'
      fullPath: '/_shell'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/_shell/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/': {
      id: '/_shell/projects/'
      path: '/projects'
      fullPath: '/_shell/projects/'
      preLoaderRoute: typeof ShellProjectsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/workspaces/new': {
      id: '/_shell/workspaces/new'
      path: '/workspaces/new'
      fullPath: '/_shell/workspaces/new'
      preLoaderRoute: typeof ShellWorkspacesNewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/workspaces/$wsId': {
      id: '/_shell/workspaces/$wsId'
      path: '/workspaces/$wsId'
      fullPath: '/_shell/workspaces/$wsId'
      preLoaderRoute: typeof ShellWorkspacesWsIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/chat/$chatId': {
      id: '/_shell/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/_shell/chat/$chatId'
      preLoaderRoute: typeof ShellChatChatIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/workspaces/$wsId/': {
      id: '/_shell/workspaces/$wsId/'
      path: '/'
      fullPath: '/_shell/workspaces/$wsId/'
      preLoaderRoute: typeof ShellWorkspacesWsIdIndexRouteImport
      parentRoute: typeof ShellWorkspacesWsIdRoute
    }
  }
}

interface ShellWorkspacesWsIdRouteChildren {
  ShellWorkspacesWsIdIndexRoute: typeof ShellWorkspacesWsIdIndexRoute
}

const ShellWorkspacesWsIdRouteChildren: ShellWorkspacesWsIdRouteChildren = {
  ShellWorkspacesWsIdIndexRoute: ShellWorkspacesWsIdIndexRoute,
}

const ShellWorkspacesWsIdRouteWithChildren = ShellWorkspacesWsIdRoute._addFileChildren(
  ShellWorkspacesWsIdRouteChildren,
)

interface ShellRouteChildren {
  ShellIndexRoute: typeof ShellIndexRoute
  ShellChatChatIdRoute: typeof ShellChatChatIdRoute
  ShellWorkspacesWsIdRoute: typeof ShellWorkspacesWsIdRouteWithChildren
  ShellWorkspacesNewRoute: typeof ShellWorkspacesNewRoute
  ShellProjectsIndexRoute: typeof ShellProjectsIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellIndexRoute: ShellIndexRoute,
  ShellChatChatIdRoute: ShellChatChatIdRoute,
  ShellWorkspacesWsIdRoute: ShellWorkspacesWsIdRouteWithChildren,
  ShellWorkspacesNewRoute: ShellWorkspacesNewRoute,
  ShellProjectsIndexRoute: ShellProjectsIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
