/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OobeRouteImport } from './routes/oobe'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellIdeProjectIdHomeRouteImport } from './routes/_shell/ide/$projectId/home'
import { Route as ShellIdeProjectIdRepoIdWsIdRouteImport } from './routes/_shell/ide/$projectId/$repoId/$wsId'
import { Route as ShellIdeProjectIdRepoIdWsIdIndexRouteImport } from './routes/_shell/ide/$projectId/$repoId/$wsId/index'

const OobeRoute = OobeRouteImport.update({
  id: '/oobe',
  path: '/oobe',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellIdeProjectIdHomeRoute = ShellIdeProjectIdHomeRouteImport.update({
  id: '/ide/$projectId/home',
  path: '/ide/$projectId/home',
  getParentRoute: () => ShellRoute,
} as any)
const ShellIdeProjectIdRepoIdWsIdRoute =
  ShellIdeProjectIdRepoIdWsIdRouteImport.update({
    id: '/ide/$projectId/$repoId/$wsId',
    path: '/ide/$projectId/$repoId/$wsId',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellIdeProjectIdRepoIdWsIdIndexRoute =
  ShellIdeProjectIdRepoIdWsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShellIdeProjectIdRepoIdWsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/oobe': typeof OobeRoute
  '/ide/$projectId/home': typeof ShellIdeProjectIdHomeRoute
  '/ide/$projectId/$repoId/$wsId': typeof ShellIdeProjectIdRepoIdWsIdRouteWithChildren
  '/ide/$projectId/$repoId/$wsId/': typeof ShellIdeProjectIdRepoIdWsIdIndexRoute
}
export interface FileRoutesByTo {
  '/oobe': typeof OobeRoute
  '/': typeof ShellIndexRoute
  '/ide/$projectId/home': typeof ShellIdeProjectIdHomeRoute
  '/ide/$projectId/$repoId/$wsId': typeof ShellIdeProjectIdRepoIdWsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/oobe': typeof OobeRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/ide/$projectId/home': typeof ShellIdeProjectIdHomeRoute
  '/_shell/ide/$projectId/$repoId/$wsId': typeof ShellIdeProjectIdRepoIdWsIdRouteWithChildren
  '/_shell/ide/$projectId/$repoId/$wsId/': typeof ShellIdeProjectIdRepoIdWsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/oobe'
    | '/ide/$projectId/home'
    | '/ide/$projectId/$repoId/$wsId'
    | '/ide/$projectId/$repoId/$wsId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/oobe' | '/' | '/ide/$projectId/home' | '/ide/$projectId/$repoId/$wsId'
  id:
    | '__root__'
    | '/_shell'
    | '/oobe'
    | '/_shell/'
    | '/_shell/ide/$projectId/home'
    | '/_shell/ide/$projectId/$repoId/$wsId'
    | '/_shell/ide/$projectId/$repoId/$wsId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  OobeRoute: typeof OobeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/oobe': {
      id: '/oobe'
      path: '/oobe'
      fullPath: '/oobe'
      preLoaderRoute: typeof OobeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/ide/$projectId/home': {
      id: '/_shell/ide/$projectId/home'
      path: '/ide/$projectId/home'
      fullPath: '/ide/$projectId/home'
      preLoaderRoute: typeof ShellIdeProjectIdHomeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/ide/$projectId/$repoId/$wsId': {
      id: '/_shell/ide/$projectId/$repoId/$wsId'
      path: '/ide/$projectId/$repoId/$wsId'
      fullPath: '/ide/$projectId/$repoId/$wsId'
      preLoaderRoute: typeof ShellIdeProjectIdRepoIdWsIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/ide/$projectId/$repoId/$wsId/': {
      id: '/_shell/ide/$projectId/$repoId/$wsId/'
      path: '/'
      fullPath: '/ide/$projectId/$repoId/$wsId/'
      preLoaderRoute: typeof ShellIdeProjectIdRepoIdWsIdIndexRouteImport
      parentRoute: typeof ShellIdeProjectIdRepoIdWsIdRoute
    }
  }
}

interface ShellIdeProjectIdRepoIdWsIdRouteChildren {
  ShellIdeProjectIdRepoIdWsIdIndexRoute: typeof ShellIdeProjectIdRepoIdWsIdIndexRoute
}

const ShellIdeProjectIdRepoIdWsIdRouteChildren: ShellIdeProjectIdRepoIdWsIdRouteChildren =
  {
    ShellIdeProjectIdRepoIdWsIdIndexRoute:
      ShellIdeProjectIdRepoIdWsIdIndexRoute,
  }

const ShellIdeProjectIdRepoIdWsIdRouteWithChildren =
  ShellIdeProjectIdRepoIdWsIdRoute._addFileChildren(
    ShellIdeProjectIdRepoIdWsIdRouteChildren,
  )

interface ShellRouteChildren {
  ShellIndexRoute: typeof ShellIndexRoute
  ShellIdeProjectIdHomeRoute: typeof ShellIdeProjectIdHomeRoute
  ShellIdeProjectIdRepoIdWsIdRoute: typeof ShellIdeProjectIdRepoIdWsIdRouteWithChildren
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellIndexRoute: ShellIndexRoute,
  ShellIdeProjectIdHomeRoute: ShellIdeProjectIdHomeRoute,
  ShellIdeProjectIdRepoIdWsIdRoute:
    ShellIdeProjectIdRepoIdWsIdRouteWithChildren,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  OobeRoute: OobeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
