// @generated by native/tools/protogen — DO NOT EDIT
#![allow(non_snake_case, clippy::all)]

/// CreateItemBody is a named request body.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateItemBody {
    /// Name is required.
    pub name: String,
    /// Status is optional.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<super::fixture_types::Status>,
}

/// Item exercises every field shape the generator has to lower.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Item {
    /// ID is the entity id.
    pub id: String,
    /// CreatedAt is when it was created.
    #[serde(rename = "createdAt")]
    pub created_at: String,
    pub meta: super::fixture_types::Meta,
    /// Name is a plain required string.
    pub name: String,
    /// Description is omitted when empty.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Parent is a pointer, so it can be null or absent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent: Option<String>,
    /// Child is a pointer to a struct with no omitempty: null, never absent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub child: Option<super::fixture_types::Nested>,
    /// Tags is a slice; a nil slice marshals as null.
    #[serde(default, deserialize_with = "super::null_default::null_to_default")]
    pub tags: Vec<String>,
    /// Items is a slice of structs, omitted when empty.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<super::fixture_types::Nested>>,
    /// Counts is a map of ints.
    #[serde(default, deserialize_with = "super::null_default::null_to_default")]
    pub counts: std::collections::HashMap<String, i64>,
    /// Extra is an untyped map: arbitrary JSON.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extra: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Raw is a raw JSON message.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub raw: Option<serde_json::Value>,
    /// Blob is a byte slice, which encoding/json base64-encodes to a string.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub blob: Option<String>,
    /// Status is the enum.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<super::fixture_types::Status>,
    /// Kind is a named string with no constants.
    pub kind: super::fixture_types::Untagged,
    /// Type collides with a Rust keyword and forces an explicit rename.
    #[serde(rename = "type")]
    pub type_: String,
    /// Size is an int64: a JSON number, not a string.
    pub size: i64,
    /// Ratio is a float.
    pub ratio: f64,
    /// Done is a bool omitted when false.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub done: Option<bool>,
}

/// Lossy carries a field the generator cannot lower: an anonymous struct nested
/// inside a slice has no name to emit, so the field is dropped and the type is
/// reported INCOMPLETE rather than quietly shipped a field short.
/// INCOMPLETE: protogen could not lower every field of this type.
/// - example.com/fixture/types.Lossy.Rows: field type []struct{Value string "json:\"value\""} did not resolve, so the field is missing from the generated struct
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Lossy {
    /// Name is fine.
    pub name: String,
}

/// Meta is embedded into Item WITH a json tag, so it stays a nested object.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Meta {
    /// Author is who made the change.
    pub author: String,
}

/// Nested is a plain struct used as a field type.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Nested {
    /// Label is the display label.
    pub label: String,
    /// Count is a counter.
    pub count: i64,
}

/// Status is a named string type with a package-level constant set, which is
/// what makes it an enum rather than a bare string alias.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum Status {
    /// StatusLocked is an item held elsewhere.
    #[serde(rename = "locked")]
    Locked,
    /// StatusNew is a freshly created item.
    #[serde(rename = "new")]
    New,
    /// StatusPRConflicts is an item whose merge would conflict.
    #[serde(rename = "pr-conflicts")]
    PrConflicts,
    /// Any other value the daemon sends, including the zero value "".
    #[serde(untagged)]
    Other(String),
}

/// TreeNode is self-referential, which the transitive closure must not recurse
/// into forever.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TreeNode {
    /// Name is the node name.
    pub name: String,
    /// Children are the child nodes.
    #[serde(default, deserialize_with = "super::null_default::null_to_default")]
    pub children: Vec<super::fixture_types::TreeNode>,
}

/// Untagged is a named string type with no constants: an alias, not an enum.
pub type Untagged = String;
