// @generated by native/tools/protogen — DO NOT EDIT
#![allow(non_snake_case, clippy::all)]

/// outlineResponse is the payload of GET /outline. It is written by hand rather
/// than through libs.WriteQueryOK, which is the whole point of it: a handler
/// that streams its envelope straight into the response writer never touches
/// gin's JSON render, and protogen used to classify exactly that as a body-less
/// success and drop the payload's types on the floor.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OutlineResponse {
    /// Files is the outline of every changed file.
    #[serde(default, deserialize_with = "super::null_default::null_to_default")]
    pub files: Vec<super::fixture_types::Nested>,
}

/// RenameItemRequest is the anonymous request body RenameItem binds for PATCH /v0/projects/:projectId/items/:id.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RenameItemRequest {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
}

/// StageRequest is the anonymous request body Stage binds for POST /v0/projects/:projectId/stage.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StageRequest {
    #[serde(default, deserialize_with = "super::null_default::null_to_default")]
    pub paths: Vec<String>,
}
