// @generated by native/tools/protogen — DO NOT EDIT
#![allow(non_snake_case, clippy::all)]

/// RenameItemRequest is the anonymous request body RenameItem binds for PATCH /v0/projects/:projectId/items/:id.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RenameItemRequest {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
}

/// StageRequest is the anonymous request body Stage binds for POST /v0/projects/:projectId/stage.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StageRequest {
    #[serde(default, deserialize_with = "super::null_default::null_to_default")]
    pub paths: Vec<String>,
}
