// @generated by native/tools/protogen — DO NOT EDIT
#![allow(non_snake_case, clippy::all)]

/// Envelope is the uniform response body returned by every v0 handler:
/// success is true for query and mutation responses and false for errors,
/// error carries the message on failure, and data carries the payload.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Envelope<T> {
    pub success: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<T>,
}

/// MutationID is the fixed data shape of a mutation response:
/// the id of the affected entity.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MutationID {
    pub id: String,
}
