// @generated by native/tools/protogen — DO NOT EDIT
#![allow(non_snake_case, clippy::all)]

/// H is a shortcut for map[string]any.
pub type H = std::collections::HashMap<String, serde_json::Value>;
