// @generated by native/tools/protogen — DO NOT EDIT
//
// Wire DTOs for the Crowbar daemon's v0 HTTP surface, generated from the Go
// handlers. One module per Go package.
//
// Encoding notes, all of which mirror what encoding/json actually does:
//   * time.Time is a String (RFC 3339, as time.Time's MarshalJSON writes it).
//   * int64/uint64 are i64/u64 numbers; the daemon uses no `,string` tags.
//   * []byte is a String (encoding/json base64-encodes it).
//   * A nil Go slice or map marshals as null, so non-optional container
//     fields deserialise null as an empty collection.
//   * Named Go string types carry an `Other(String)` fallback, because a Go
//     string constant set is open: the zero value "" is a legal value the
//     constants never name.

pub mod fixture_handlers;
pub mod fixture_libs;
pub mod fixture_types;
pub mod gin_gonic_gin;
pub mod null_default;
