// @generated by native/tools/protogen — DO NOT EDIT
//
// Go marshals a nil slice or map as JSON null rather than omitting it, and
// serde refuses null for Vec/HashMap. Every non-optional container field
// deserialises through this helper so a nil-on-the-wire collection arrives as
// an empty one instead of failing the whole response.

use serde::Deserialize;

/// Deserialise T, mapping a JSON null onto T::default().
pub fn null_to_default<'de, D, T>(
    deserializer: D,
) -> Result<T, D::Error>
where
    D: serde::Deserializer<'de>,
    T: Default + Deserialize<'de>,
{
    Ok(Option::<T>::deserialize(deserializer)?.unwrap_or_default())
}
